<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
		<RootNamespace>ClientUser</RootNamespace>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<Platforms>x86;x64;ARM64</Platforms>
		<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
		<PublishProfile>win-$(Platform).pubxml</PublishProfile>
		<UseWinUI>true</UseWinUI>
		<EnableMsixTooling>true</EnableMsixTooling>
		<Nullable>enable</Nullable>
		<WindowsPackageType>None</WindowsPackageType>
		<WindowsAppSDKSelfContained>false</WindowsAppSDKSelfContained>
		<SelfContained>false</SelfContained>
		<ApplicationIcon>Assets\logo.ico</ApplicationIcon>


		<EnableDefaultCompileItems>true</EnableDefaultCompileItems>
<PublishTrimmed>true</PublishTrimmed>
	</PropertyGroup>
	<ItemGroup>
	  <Compile Include="..\ApiConfig.cs" Link="ApiConfig.cs" />
	</ItemGroup>

	<!-- Asset e Manifest (standard) -->
	<ItemGroup>
		<Content Include="Assets\SplashScreen.scale-200.png" />
		<Content Include="Assets\LockScreenLogo.scale-200.png" />
		<Content Include="Assets\Square150x150Logo.scale-200.png" />
		<Content Include="Assets\Square44x44Logo.scale-200.png" />
		<Content Include="Assets\Square44x44Logo.targetsize-24_altform-unplated.png" />
		<Content Include="Assets\StoreLogo.png" />
		<Content Include="Assets\Wide310x150Logo.scale-200.png" />
	</ItemGroup>
	<ItemGroup>
		<Manifest Include="$(ApplicationManifest)" />
	</ItemGroup>

	<!-- Pacchetto NuGet WinUI 3 -->
	<ItemGroup>
		<!-- Assicurati che la versione sia coerente con ClientIT, es: 1.5.240428000 -->
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.251106002" />
	</ItemGroup>

	<!-- 3. DEFINIZIONE MANUALE DEI FILE (Ora è l'unica fonte) -->
	

	<!-- Proprietà MSIX (standard) -->
	<ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
		<ProjectCapability Include="Msix" />
	</ItemGroup>
	<ItemGroup>
	  <Content Update="Assets\logo.ico">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Controls\TicketDetailDialog.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
		<HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
	</PropertyGroup>
	<PropertyGroup>
		<PublishReadyToRun Condition="'$(Configuration)' == 'Debug'">False</PublishReadyToRun>
		<PublishReadyToRun Condition="'$(Configuration)' != 'Debug'">true</PublishReadyToRun>
		<PublishTrimmed Condition="'$(Configuration)' == 'Debug'">False</PublishTrimmed>
		<PublishTrimmed Condition="'$(Configuration)' != 'Debug'">False</PublishTrimmed>
		<ApplicationIcon>Assets\logo.ico</ApplicationIcon>
		<AssemblyName>ZblbTicket</AssemblyName>
		<PackageCertificateThumbprint></PackageCertificateThumbprint>
		<PackageCertificateKeyFile>certUser.pfx</PackageCertificateKeyFile>
		<PackageCertificatePassword>197345</PackageCertificatePassword>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'">
	  <Optimize>True</Optimize>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
	  <Optimize>True</Optimize>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|ARM64'">
	  <Optimize>True</Optimize>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x86'">
	  <Optimize>True</Optimize>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
	  <Optimize>True</Optimize>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|ARM64'">
	  <Optimize>True</Optimize>
	</PropertyGroup>
</Project>